version: "3.9"
services:
  fraud-api:
    build: .
    container_name: fraud-detection-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./saved_models:/app/saved_models
      - ./reports:/app/reports
    restart: unless-stopped

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow-server
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlflow/mlruns
    restart: unless-stopped
